socialappslab/denguechatPlus-web

.github/workflows/build.yml
Dockerfile

Added workflow to build the container when a push is made to develop

Added workflow to build container

---

src/i18n/locales/en/splash.json
src/i18n/locales/en/translation.json
src/i18n/locales/es/splash.json
src/i18n/locales/es/translation.json
src/layout/AppBar.tsx
src/layout/BaseLayout.tsx
src/layout/Footer.tsx
src/layout/PageLayout.tsx
src/pages/Splash.tsx

Updates the footer to be consistent with page layout

fix: Update footer to be on page layout

---

src/i18n/locales/en/splash.json
src/i18n/locales/es/splash.json
src/i18n/locales/pt/splash.json
src/pages/Splash.tsx

Implements [DNG-214](https://denguechat.atlassian.net/browse/DNG-214)

Changes Splash Screen

---

src/i18n/locales/en/splash.json
src/i18n/locales/es/splash.json
src/i18n/locales/pt/splash.json

Remove missed Zika and Chikungunya text

Remove all Zika and Chikungunya text

---

.env.development
src/pages/admin/CreateCityDialog.tsx
src/pages/admin/EditCityPage.tsx
src/schemas/create.ts
src/schemas/update.ts

Small casing update in `neighborhoods_attributes` at `/cities` endpoint

(chore): Update casing

---

.env.development

Fixes https://github.com/socialappslab/denguechatPlus-web/pull/23/files#diff-da4c41d59c967338247b2f0ea6d845ab05171f942fd9521b96d3304202185db9L2

(fix): development environment config

---

src/themed/table/DataTable.tsx

Fixes [DNG-232](https://denguechat.atlassian.net/browse/DNG-232)

(fix): Fix pagination

---

src/schemas/auth.ts

Small fix on UserProfile types

(fix): Improve UserProfile typing

---

src/pages/admin/CreateCityDialog.tsx
src/pages/admin/EditCityPage.tsx
src/pages/loader/LoadCity.tsx

Fixes typing from `UserProfile` types

(fix): Update typing

---

src/components/list/CityList.tsx

(fix): Fix typing

---

src/pages/admin/CreateCityDialog.tsx

(chore): Add comment on type casting

---

src/components/dialog/CreateCityDialog.tsx
src/components/dialog/CreateRoleDialog.tsx
src/components/dialog/EditRoleDialog.tsx
src/schemas/update.ts

(fix): Roles typing errors

---

src/components/dialog/AssignMembersDialog.tsx
src/components/dialog/CreateCityDialog.tsx
src/components/dialog/CreateRoleDialog.tsx
src/components/dialog/EditRoleDialog.tsx
src/components/list/RoleList.tsx
src/components/list/TeamsList.tsx
src/constants/index.ts
src/i18n/locales/en/admin.json
src/i18n/locales/en/permissions.json
src/i18n/locales/en/translation.json
src/i18n/locales/es/admin.json
src/i18n/locales/es/permissions.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/admin.json
src/i18n/locales/pt/permissions.json
src/i18n/locales/pt/register.json
src/i18n/locales/pt/translation.json
src/pages/admin/EditCityPage.tsx
src/schemas/entities.ts
src/schemas/index.ts
src/schemas/update.ts

Implements assign members
**Demo**

(feat): Assign members

---

src/components/dialog/AssignMembersDialog.tsx
src/schemas/update.ts

(fix): Update Member Assignment Object

---

src/i18n/locales/en/permissions.json
src/i18n/locales/es/permissions.json
src/i18n/locales/pt/permissions.json

Small update on permissions i18n

(fix): Update permissions i18n

---

.env.development
src/components/dialog/AssignMembersDialog.tsx
src/components/list/TeamsList.tsx
src/i18n/locales/en/translation.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/translation.json
src/schemas/entities.ts

This PR implements [DNG-238](https://denguechat.atlassian.net/browse/DNG-238)

fix: Add missing columns to Brigades list

---

src/components/dialog/CreateTeamDialog.tsx
src/components/list/TeamsList.tsx
src/i18n/locales/en/admin.json
src/i18n/locales/es/admin.json
src/i18n/locales/pt/admin.json
src/schemas/create.ts
src/util/index.ts

Implements [#60](https://denguechat.atlassian.net/browse/DNG-60)

feat: Create Brigades

---

src/pages/admin/HomeAdmin.tsx
src/routes/AppRouter.tsx

feat: add redirect on home

---

src/pages/my-city/MyCityPage.tsx

This PR adds House Reports to My City page

feat: Add house reports to city

---

src/i18n/locales/en/myCity.json
src/i18n/locales/es/myCity.json
src/i18n/locales/pt/myCity.json
src/pages/my-city/MyCityPage.tsx

This PR implements [46: List Posts by City](https://denguechat.atlassian.net/browse/DNG-46)

feat: Add sort

---

src/i18n/locales/en/myCity.json
src/i18n/locales/es/myCity.json
src/i18n/locales/pt/myCity.json
src/pages/my-city/MyCityPage.tsx
src/schemas/entities.ts
src/themed/loader/Loader.tsx

This PR adds fixes to the My City section

fix: Web fixes

---

src/components/dialog/CreateCityDialog.tsx
src/components/dialog/CreateTeamDialog.tsx

This PR fixes [392: Create Brigade](https://denguechat.atlassian.net/browse/DNG-392)

fix: Create Brigade

---

.env.production

This PR is part of [389: Setup Github pipelines to production](https://denguechat.atlassian.net/jira/software/projects/DNG/boards/1?assignee=712020%3A874817f0-6b35-4108-a176-0a2c55d75016&selectedIssue=DNG-389)
It populates `.env.production` that will trigger builds to `main`.

feat: Add production environment

---

src/components/RiskChart.tsx
src/components/SitesReport.tsx
src/pages/my-community/MyCommunityPage.tsx
src/routes/AppRouter.tsx
src/themed/progress-bar/ProgressBar.tsx

This PR also adds a fix to `ProgressBar` to render colors correctly.

fix: Fix router to redirect to HomePage

---

src/pages/my-community/MyCommunityPage.tsx

This PR adds an embed from LookerStudio ([58](https://denguechat.atlassian.net/browse/DNG-58))

feat: Add risk report

---

src/pages/my-city/MyCityPage.tsx

fix: label

---

src/components/dialog/CreateTeamDialog.tsx
src/i18n/locales/en/admin.json
src/i18n/locales/es/admin.json
src/i18n/locales/pt/admin.json

This PR implementes [423](https://denguechat.atlassian.net/browse/DNG-423)

feat: Add city to create brigade form

---

.env.development
package.json
src/main.tsx

This PR integrates Rollbar: [354](https://denguechat.atlassian.net/browse/DNG-354). We need however to set hidden envs.

feat: Setup Rollbar

---

src/components/SelectLanguageComponent.tsx
src/components/dialog/CreateTeamDialog.tsx
src/layout/AppBar.tsx
src/layout/BaseLayout.tsx

This PR updates the web layout to have Language Selection and Logout on the sidebar.

fix: Layout

---

src/components/list/RankViewBox.tsx

This PR implements Isologos on Rankings

feat: Add isologo to ranking

---

src/i18n/locales/en/admin.json
src/i18n/locales/es/admin.json
src/i18n/locales/pt/admin.json

This PR implements [445](https://denguechat.atlassian.net/browse/DNG-445)

fix: Capitalize titles

---

src/components/dialog/CreateTeamDialog.tsx
src/schemas/create.ts

This PR fixes [427](https://denguechat.atlassian.net/browse/DNG-427), by removing it.

fix: Remove team leader

---

src/pages/my-city/MyCityPage.tsx
src/routes/AppRouter.tsx

This PR fixes [447](https://denguechat.atlassian.net/browse/DNG-447)

fix: The filter is not working as expected

---

src/i18n/locales/en/feed.json
src/i18n/locales/pt/feed.json
src/layout/AppBar.tsx
src/pages/reports/HeatMapPage.tsx
src/pages/reports/SitesPage.tsx
src/pages/reports/VisitPage.tsx

fix: fix reports translations 

---

src/components/dialog/CreateTeamDialog.tsx
src/i18n/locales/en/admin.json
src/i18n/locales/en/translation.json
src/i18n/locales/es/admin.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/admin.json
src/i18n/locales/pt/translation.json

fix: fix labels and the team form(fields orders)

fix: fix labels and the team form(fields orders)

---

README.md
index.html
src/App.tsx
src/i18n/locales/en/splash.json
src/i18n/locales/en/translation.json
src/i18n/locales/es/splash.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/splash.json
src/i18n/locales/pt/translation.json

Change all labels and text from denguechat+ to DengueChatPlus

fix: change all labels and text from denguechat+ to DengueChatPlus

---

src/util/index.ts

fix: change date format on tables

fix: change date format on tables

---

src/pages/my-community/MyCommunityPage.tsx

fix: update the risk chart url in my community page

fix: update the risk chart url in my community page

---

src/layout/BaseLayout.tsx

fix: fix footer

---

src/layout/BaseLayout.tsx
src/layout/Footer.tsx
src/layout/PageLayout.tsx
src/layout/PublicPageLayout.tsx
src/pages/auth/NewPasswordPage.tsx

revert footer changes

---

src/pages/auth/ResetPasswordPage.tsx

fix: allow all numbers to reset their passwords

fix: allow all numbers to reset their passwords

---

src/i18n/locales/en/errorCodes.json
src/i18n/locales/es/errorCodes.json
src/i18n/locales/pt/errorCodes.json
src/pages/auth/ResetPasswordPage.tsx

Forgot password - Handle Error Message for Mismatched User Details in Reset Password Form

fix: fix the error message to the user, change the phone number input

---

src/components/SitesReport.tsx

fix: fix tariki house counter

---

src/pages/auth/ValidateCodePage.tsx

fix: Fix the tariki houses endpoint

fix: Fix the tariki houses endpoint

---

src/layout/Footer.tsx

fix: fix footer links

---

src/constants/permissions.ts
src/layout/AppBar.tsx

fix: check the permission for vists and reports modules

fix: check the permission for vists and reports modules

---

src/components/dialog/AssignMembersDialog.tsx

fix: fix  the paginator for members in brigade

fix: fix  the paginator for members in brigade

---

src/pages/my-community/MyCommunityPage.tsx
src/pages/reports/HeatMapPage.tsx
src/pages/reports/SitesPage.tsx
src/pages/reports/VisitPage.tsx

fix: fix the reports iframe attributes because they block the download feature

fix: fix the reports iframe attributes

---

src/components/RiskChart.tsx

fix: fix the report name in my city

fix: fix the report name in my city

---

src/components/SitesReport.tsx

fix: fix the green container quantity in my comunity

fix: fix the green container quantity in my comunity

---

src/components/SitesReport.tsx
src/i18n/locales/en/feed.json
src/i18n/locales/es/feed.json
src/i18n/locales/pt/feed.json
src/themed/progress-bar/ProgressBar.tsx

fix: fix add description below progress bar in comunity page

fix: fix add description below progress bar in comunity page

---

Dockerfile

fix: docker version

---

src/layout/AppBar.tsx

fix: hide unused options

---

package.json
src/components/dialog/EditInspectionDialog.tsx
src/i18n/locales/en/admin.json
src/i18n/locales/en/errorCodes.json
src/i18n/locales/es/admin.json
src/i18n/locales/es/errorCodes.json
src/i18n/locales/pt/admin.json
src/i18n/locales/pt/errorCodes.json
src/pages/visits/EditVisitPage.tsx
src/schemas/entities.ts
src/schemas/update.ts
src/themed/form-input/FormInput.tsx

[DNG-142](https://denguechat.atlassian.net/browse/DNG-142)

feat: edit inspection

---

src/components/list/HouseBlockList.tsx
src/constants/permissions.ts
src/i18n/locales/en/translation.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/translation.json
src/layout/AppBar.tsx
src/routes/AppRouter.tsx

[DNG-599](https://denguechat.atlassian.net/browse/DNG-599)

feat: house block's list

---

src/components/dialog/EditHouseBlockDialog.tsx
src/components/list/HouseBlockList.tsx
src/i18n/locales/en/admin.json
src/i18n/locales/en/translation.json
src/i18n/locales/es/admin.json
src/i18n/locales/pt/admin.json
src/schemas/entities.ts
src/schemas/update.ts

[GNB-598](https://denguechat.atlassian.net/browse/DNG-598)

feat: edit frente a frente

---

src/i18n/locales/es/admin.json
src/pages/visits/VisitsPage.tsx
src/schemas/entities.ts

[DNG-688](https://denguechat.atlassian.net/browse/DNG-688)

fix: Site info on Visit List

---

src/pages/visits/EditVisitPage.tsx
src/schemas/entities.ts
src/schemas/update.ts
src/themed/form-select-autocomplete/FormSelectAutocomplete.tsx
src/util/ControllerAutoComplete.tsx
src/util/index.ts

[DNG-682](https://denguechat.atlassian.net/browse/DNG-682)

fix: site list in edit visit with autocomplete

---

src/i18n/locales/en/questionnaire.json
src/i18n/locales/es/questionnaire.json
src/i18n/locales/pt/questionnaire.json
src/pages/visits/EditVisitPage.tsx
src/schemas/entities.ts
src/schemas/update.ts

[DNG-682](https://denguechat.atlassian.net/browse/DNG-682)

fix: host multi select

---

src/i18n/locales/en/translation.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/translation.json

[DNG-528](https://denguechat.atlassian.net/browse/DNG-528)

fix: change column name from "Visit Status" to "State of Site" in Visits page

---

src/i18n/locales/en/translation.json
src/i18n/locales/es/translation.json
src/i18n/locales/pt/translation.json
src/layout/Footer.tsx

[DNG-728](https://denguechat.atlassian.net/browse/DNG-728)

feat: add "How to use Offline Mode" link in footer

---

src/layout/AppBar.tsx

[DNG-739](https://denguechat.atlassian.net/browse/DNG-739)

feat: add link to iquitos' website in the header

---

src/i18n/locales/en/splash.json
src/i18n/locales/es/splash.json
src/i18n/locales/pt/splash.json
src/pages/Splash.tsx

[DNG-741](https://denguechat.atlassian.net/browse/DNG-741)

feat: add "User Guide" section

---

src/components/dialog/EditInspectionDialog.tsx

[DNG-764](https://denguechat.atlassian.net/browse/DNG-764)

When selecting "Other" option the other field should be enabled

---

package.json
src/instrument.js
src/main.tsx

feat: integration with sentry

---

src/pages/auth/CreateAccountPage.tsx
src/themed/form-select/FormSelect.tsx

[DNG-777](https://denguechat.atlassian.net/browse/DNG-777)

Show asterisks for required fields in the register page

---

src/components/dialog/CreateTeamDialog.tsx
src/i18n/locales/en/register.json
src/schemas/index.ts
src/themed/form-select/FormSelect.tsx

[DNG-774](https://denguechat.atlassian.net/browse/DNG-774)

Filter wedges by selected sector when creating a brigade

---

src/components/dialog/EditInspectionDialog.tsx
src/schemas/entities.ts
src/schemas/update.ts

[DNG-818](https://denguechat.atlassian.net/browse/DNG-818)

Display and send water source correctly as multiple values

---

src/components/dialog/EditInspectionDialog.tsx
src/schemas/entities.ts
src/schemas/update.ts

[DNG-869](https://denguechat.atlassian.net/browse/DNG-869)

Change `eliminationMethodType` to multiselect

---

src/components/dialog/EditInspectionDialog.tsx
src/pages/visits/EditVisitPage.tsx
src/schemas/update.ts

[DNG-930](https://denguechat.atlassian.net/browse/DNG-930)

Remove `hasWater` edit field since we always sent that to `true` from the app

---

src/i18n/locales/en/admin.json
src/i18n/locales/es/admin.json
src/i18n/locales/pt/admin.json
src/pages/visits/EditVisitPage.tsx
src/schemas/entities.ts
src/schemas/update.ts

[DNG-954](https://denguechat.atlassian.net/browse/DNG-954)

Show and update "other" field for `familyEducationTopics`

---

src/components/dialog/EditHouseBlockDialog.tsx
src/components/list/HouseBlockList.tsx
src/hooks/useHouseBlockTypeToLabel.tsx
src/i18n/locales/en/admin.json
src/i18n/locales/en/common.json
src/i18n/locales/en/errorCodes.json
src/i18n/locales/en/permissions.json
src/i18n/locales/en/register.json
src/i18n/locales/en/translation.json
src/i18n/locales/en/validation.json
src/i18n/locales/es/admin.json
src/i18n/locales/es/common.json
src/i18n/locales/es/errorCodes.json
src/i18n/locales/es/register.json
src/i18n/locales/es/translation.json
src/i18n/locales/es/validation.json
src/i18n/locales/pt/admin.json
src/i18n/locales/pt/common.json
src/i18n/locales/pt/errorCodes.json
src/i18n/locales/pt/translation.json
src/layout/Sidebar.tsx
src/pages/admin/EditUserPage.tsx
src/schemas/entities.ts
src/schemas/update.ts
src/themed/form-select/FormSelect.tsx
src/types/resources.ts

- [DNG-944](https://denguechat.atlassian.net/browse/DNG-944)
- [DNG-945](https://denguechat.atlassian.net/browse/DNG-945)
- [DNG-946](https://denguechat.atlassian.net/browse/DNG-946)

House groups implementation
